title: Eric Krause Obscura
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Optional: pick a skin (prebuilt color scheme)
minimal_mistakes_skin: "dark"

# Basic site settings
author:
  name: "Eric Krause"
  email: "you@example.com"
paginate: 5

# Main navigation links
main:
  - title: "Home"
    url: /
  - title: "About the Artist"
    url: /about/
  - title: "Portfolio"
    url: /portfolio/
  - title: "Contact"
    url: /contact/

# Enable navigation bar
defaults:
  - scope:
      path: ""
    values:
      navigation: main
