title: Eric Krause Obscura Portfolio
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Optional: pick a skin (prebuilt color scheme)
minimal_mistakes_skin: "dark"

# Basic site settings
author:
  name: "Your Name"
  email: "you@example.com"
paginate: 5
